export enum ActionTypes {
  RESET = 'RESET',
  CLEAR = 'CLEAR',
  SAVE = 'SAVE',

  SET_IDENTIFY = 'SET_IDENTIFY',
  SET_QUALIFICATION = 'SET_QUALIFICATION',
  SET_WORK_EXPERIENCE = 'SET_WORK_EXPERIENCE',
  SET_SKILLED_EMPLOYMENT = 'SET_SKILLED_EMPLOYMENT',
  SET_PARTNER = 'SET_PARTNER',
  SET_FINAL = 'SET_FINAL',
}
